use_frameworks!


target 'ZCMessageModule_Example' do
#  pod 'ZCMessageModule', :path => '../'
 pod 'CTMediator'
  target 'ZCMessageModule_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
